name: reviewdog

on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          reporter: github-pr-review
